### ISSUE TITLE
Offset Bug 

### ISSUE THREAD

**Issue by eMJay1805** [Le0Michine/FusionGridfinityGenerator#31] opened 2023-06-11 19:33 UTC
When creating the base, an edge is created, which means that the container does not go in well.

![image](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/75495773/eead4fb2-f67b-4754-8bce-9c923a732fa5)

**Comment by scriptnugget** [comment] 2023-06-15 14:01
I just encountered this as well, in both the baseplate and container. In the timeline I found the cause, in both cases being the 'thicken'-command offsetting some but not all required faces. Editing the feature and reselecting the correct faces (with the chain select option on) fixes the model.

**Comment by Le0Michine** [comment] 2023-06-20 02:40
Hi,
Could you provide a screenshot with your inputs? Is that an issue with baseplate or something else? I can't reproduce it with standard values

**Comment by scriptnugget** [comment] 2023-06-20 15:26
![baseplate_settigns](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/45875510/ff199193-8802-4085-ac4d-1be1da79fb97)
![baseplate_overhang](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/45875510/ee26a02b-1aed-4dc3-9471-c8fd79d0dd9f)
![bin_settings_1](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/45875510/de1fff02-e10f-4892-92d5-bc4b46e36d83)
![bin_settings_2](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/45875510/7f328466-2bbe-4676-9d4f-69b44670bdab)
![bin_overhang](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/45875510/91b5b1f7-22ff-4aa6-a967-a16ee0704b61)

I made these screenshots without changing any input values, and this is with the latest version of the plugin. I reinstalled the plugin last week before I posted here, the issue still persisted.

**Comment by eMJay1805** [comment] 2023-06-23 16:35
Little Video
https://www.youtube.com/watch?v=bTtyo-TPZzQ

**Comment by Le0Michine** [comment] 2023-06-27 03:55
Tried to reproduce again with suggested values (seems like those are just defaults) and I'm getting a different result, not sure what could be the cause

![image](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/2707008/d3e24993-17f0-403f-b403-ee48066dad86)

**Comment by Le0Michine** [comment] 2023-06-27 04:01
noticed that on the your pictures the baseplate model doesn't have clearance between bin overhang and baseplate chamfer this might indicate that some offset operation did get executed for some reason. Can I ask you to export fusion project file and attach it here so I can inspect each operation?

**Comment by eMJay1805** [comment] 2023-06-27 16:18
[FusionGridfinityGenerator v1.zip](https://github.com/Le0Michine/FusionGridfinityGenerator/files/11884907/FusionGridfinityGenerator.v1.zip)
I only created the base and the bin. All settings are standard. 
Do you have Fusion personal edition or full version? I have the Personal Edition.

**Comment by Le0Michine** [comment] 2023-06-28 03:43
I use personal version. Looks like I can't open your file yet, seems like my fusion didn't get to update and isn't on the latest version. I don't quite see how to force it to update either


```
Forward compatibility is not supported:2.0.16490 - The file you are trying to open was last saved in a newer version of the software. It cannot be opened!
Persisted Software version: 2.0.16490

Current Software version: 2.0.15775	
```

seems like I'll have to wait for update to happen, hopefully it will catch up within a day or two

**Comment by robi000001** [comment] 2023-06-28 05:14
Hi!
I also use a recent version of fusion and encountered the same issue. All settings are default. I attach some screenshots, maybe they help.
![Gridfinity](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/51284809/c877c7c2-e613-4f77-9fec-19e9b7d3a78a)
![Gridfinity-2](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/51284809/b694bc69-de92-4302-8248-ee8b77006b29)

**Comment by robi000001** [comment] 2023-06-28 18:55
It seems that the new fusion version have a bug (or a new feature). After extending the "bin base side faces", the next feature fails to select all the relevant faces.
By omiting the line:
 222 features.extendFeatures.add(extendClearanceSurfaceFeatureInput) from baseGenerator.py, it seems to solve the problem (but I do not consider it a proper fix).
![Gridfinity-3](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/51284809/1e13896d-3d47-4722-a3bb-a5a24362fce8)
![Gridfinity-4](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/51284809/610b8bbe-b512-4bb0-be49-9e2bee539fed)
![Gridfinity-5](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/51284809/6a94bc45-f9c2-4d15-a7a9-773403098ff2)

**Comment by Le0Michine** [comment] 2023-06-29 03:22
that makes sense, I suspected something was happening around that offset operation. I'll try to play around and see if I can replace it with something else or improve stability. Will also try to reinstall fusion as it doesn't seem like it is going to find a new version

**Comment by Le0Michine** [comment] 2023-07-03 18:01
Pushed a fix, let me know if you still experience the issue after update.

Some details:
looks like the issue was caused by some internal changes in fusion. To get clearance for bins to sit into the baseplate I use thickening feature. To do that I create surface with 0 offset from the bin base walls. At this point I get 24 faces. Then I extend  the top faces up to ensure clean cut with the baseplate. In earlier fusion versions the amount of faces on the object referencing surface offset feature would still be 24, but with the newer version the top 8 faces used with extend feature are removed from that list. The commit above adds those missing faces explicitly to make sure they are not omitted anymore.

**Comment by robi000001** [comment] 2023-07-03 18:35
The fix seems to work perfectly :)
Thank you.
![Gridfinity-b1](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/51284809/89e658ac-b07e-4f3a-941a-de3199315dbe)
![Gridfinity-b2](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/51284809/1a78ad12-47fe-43da-8da5-75b17050543d)

**Comment by Le0Michine** [comment] 2023-07-03 19:38
thanks for confirmation

**Closed by Le0Michine** 2023-07-03 19:38 UTC
