### ISSUE TITLE
"Generate Lip for stackability" option causes error

### ISSUE THREAD

**Issue by suxscribe** [Le0Michine/FusionGridfinityGenerator#26] opened 2023-05-05 10:45 UTC
Hi! 
In Gridfinity Bin dialog when I check the "Generate Lip for stackability" checkbox it throws an error

![2023-05-05 13_39_18-Autodesk Fusion 360 (Personal - Not for Commercial Use)](https://user-images.githubusercontent.com/19854626/236437589-3f32067f-3dcc-4115-9e27-dabcbc748b71.png)

Fusion 360 2.0.16009 x86_64
Active Plan: Personal
Windows 10 Pro 22H2 (19045.2846)

**Comment by Le0Michine** [comment] 2023-05-07 14:44
Hi, could you provide a screenshot with all of your inputs? I can't reproduce the issue when I select just shelled bin with a lip

**Comment by suxscribe** [comment] 2023-05-07 15:59
The issue is gone, I guess. I can't reproduce it now, and lip works fine ¯\_(ツ)_/¯

**Comment by Le0Michine** [comment] 2023-05-07 19:56
I'm gonna close it for now then, feel free to reopen if the issue will reappear

**Closed by Le0Michine** 2023-05-07 19:56 UTC
