### ISSUE TITLE
Boxes are generating with an error for 3/4 of the top lip.

### ISSUE THREAD

**Issue by Twinner103** [Le0Michine/FusionGridfinityGenerator#79] opened 2024-01-25 11:56 UTC
Updated Fusion now the generator doesn't generate boxes correctly, screws up the lip for 3/4 of the box. Any tips on fixing?

![image](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/157704289/0b5725e4-1cb8-4d20-9deb-b1d87ee29284)

**Comment by Le0Michine** [comment] 2024-01-26 03:16
Hi, this looks like an issue which appeared on older plugin version after fusion update. Please make sure you have the most recent version installed https://apps.autodesk.com/FUSION/en/Detail/Index?id=7197558650811789&appLang=en&os=Mac, v1.2.7.0 should solve the problem.

Let me know if you are still experiencing this issue after the upgrade

**Comment by Le0Michine** [comment] 2024-01-26 03:17
duplicate of #56

**Comment by Twinner103** [comment] 2024-01-26 11:29
That fixed it, thanks!

Kevin Armitage

________________________________

**Closed** 2024-01-27 04:21 UTC
Labels: duplicate
