### ISSUE TITLE
Bin Bottom Options - With screw holes + magnet cutouts (Combined) not working

### ISSUE THREAD

**Issue by Pauly-gon** [Le0Michine/FusionGridfinityGenerator#43] opened 2023-08-21 21:45 UTC
When selecting the option to add both screw holes and magnet cutouts the combined option fails to appear on the finished bin.
Holes are not created with the rectangular cutouts leading to midair printing of a circle. 

<img width="1037" alt="FusionGridfinityGenerator - Selection View" src="https://github.com/Le0Michine/FusionGridfinityGenerator/assets/101109611/f5f4039f-1a80-4108-97ee-2a67e84d3458">

It seems like the measurements are off earlier in the timeline.
Both rectangle sketches are made in the timeline but are offset too far.

<img width="808" alt="FusionGridfinityGenerator - Sketch offset incorrect" src="https://github.com/Le0Michine/FusionGridfinityGenerator/assets/101109611/e9d97090-ef72-4073-9c32-a7a1b8fbbb5a">
<img width="865" alt="FusionGridfinityGenerator - Sketch offset incorrect2" src="https://github.com/Le0Michine/FusionGridfinityGenerator/assets/101109611/312155e6-f957-4996-8d65-f82a959ce060">

Tested issue in v1.2.4 & v1.2.3

**Comment by Le0Michine** [comment] 2023-08-23 04:21
looks like this could be caused by recent change in how those holes are positioned

**Comment by Le0Michine** [comment] 2023-08-23 04:23
should be fixed now, release will take some time

**Comment by Le0Michine** [comment] 2023-08-30 14:04
1.2.5.0 is live in autodesk store now, closing the issue

**Comment by Le0Michine** [comment] 2023-08-30 14:05
https://github.com/Le0Michine/FusionGridfinityGenerator/releases/tag/v1.2.5.0

**Closed by Le0Michine** 2023-08-30 14:04 UTC
Labels: bug
