### ISSUE TITLE
Section dividers are too high

### ISSUE THREAD

**Issue by tache** [Le0Michine/FusionGridfinityGenerator#20] opened 2023-04-20 02:32 UTC
First of all - this is awesome!

The section dividers are too high to allow proper stacking. This is a two compartment bin with wall down the middle.
## stacked
![IMG_5994](https://user-images.githubusercontent.com/594187/233242311-bc586563-2c54-4f25-bf09-3c7fa2dcb68c.png)
## Left Stackable - Right Generated
![IMG_5997](https://user-images.githubusercontent.com/594187/233260120-b02810d5-65d2-4f14-bd37-8413d838acd3.png)

**Comment by Le0Michine** [comment] 2023-04-22 02:38
Hi, thanks for pointing this out, I'll take a look

**Comment by tache** [comment] 2023-04-22 18:50
I was trying to dig into the code to do a PR, but I am not too up to speed on python and have zero knowledge of Fusion 360 plugins. I think if I understand how you build up a bin, that adding a cut on the compartment as the final step. Here I did it manually in F360. After generating, I did the extrude function, selected the compartment divider, set to cut, at 1mm - the picture is the result. When I was digging into the code, my thought was to add a "compartment height" to the `Bin compartment` of the configure dialog, so it would be configurable. 

<img width="723" alt="Screen Shot 2023-04-22 at 2 49 03 PM" src="https://user-images.githubusercontent.com/594187/233801504-2c43fc1e-b387-4f0c-a372-6a0feeb39c6d.png">

**Comment by Le0Michine** [comment] 2023-04-22 20:52
looking closer, it seems like the the depth should be right, at least comparison with original shows that it is in line with the label tab there, interesting

![image](https://user-images.githubusercontent.com/2707008/233806113-a90b027b-7520-4a8f-b203-25f04efdd0e8.png)

**Comment by Le0Michine** [comment] 2023-04-22 21:00
the distance from the base to the top of the dividers is 6u on the picture. Seems like if you add label tab you will get same issue, I'm wondering if adding a second level chamfer for the lip would help

![image](https://user-images.githubusercontent.com/2707008/233806333-1186a70e-e9bd-45ec-b407-d76c35f252ff.png)

**Comment by tnoppeney** [comment] 2023-04-23 10:47
Just by stacking two 1x1x1 containers in Fusion 360 already shows the issue:

![grafik](https://user-images.githubusercontent.com/10694722/233835267-01a46e02-0359-49e8-bbab-276a31a42fb6.png)

The overlap in my case is .35mm.

**Comment by Le0Michine** [comment] 2023-04-23 22:00
yeah, but still, not sure if reducing height of the dividers is the right approach to correct this. Ideally if you have 3 bins each 2U height they should stack and be on the same level as a single bin 6U height, so you should be able to put another bin on top of them. Something like on this picture

![image](https://user-images.githubusercontent.com/2707008/233868383-e56663d4-d001-4721-9851-63786639e718.png)

If we just cut on divider height we would get into this situation

![image](https://user-images.githubusercontent.com/2707008/233868452-1143a65a-39bf-4434-81f1-d837b1ee6bc4.png)

**Comment by Le0Michine** [comment] 2023-04-23 22:03
It seems like the lip needs to be higher, about 0.3mm or so. Which would be ~4.7mm instead of 4.4mm on top of the bin height

**Comment by Le0Michine** [comment] 2023-04-23 22:06
looking at the original design and it seems like it would have the same issue

![image](https://user-images.githubusercontent.com/2707008/233868647-96a7d315-590f-4fe9-bc4b-3c7439841ee3.png)

**Comment by tache** [comment] 2023-05-10 03:03
Any status on this one? I was thinking about maybe having the ability to set the section divider height might be an interesting  option in the dialog. I.e., you could have a 6U bin, but wanted to have a 3U divider.

**Comment by Le0Michine** [comment] 2023-05-10 04:09
sorry didn't have enough time to print these and experiment more. I don't think lowering dividers is the right way to go due to reasons mentioned above, it might solve the issue you are experiencing but it seems like it might introduce another one. I would prefer not to add an extra option either to keep UI as simple as possible.
I was going to experiment a bit with the lip clearance and height as it looks like that's the root cause

**Comment by tnoppeney** [comment] 2023-05-10 05:43
> ![image](https://user-images.githubusercontent.com/2707008/233868383-e56663d4-d001-4721-9851-63786639e718.png)

In this picture you are giving the bins tolerance on sides (there are gaps) but not on top of the divider (there is not gap).

I printed 1x1 bins with dividers and it basically is as I expected and as it has been shown by tache: the top bin sits basically on the divider of the bottom bin and you can wiggle it left or right. This is definitively not how it should be.

Printing it with a divider 0.3mm shorter (as I suggested above) eliminates the issue and the top bin sits in the bottom bin exactly the same as if it wouldn't have the divider (and that should be the correct behavior). The divider or label tab should not be responsible for making sure, that the top bin does not sink in to much, because (at least for my case) most of my bins don't have either of those.

Here is a bunch of boxes stacked together and the bottom left has a shortened divider, still everything adds up nicely:
![image](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/10694722/19032b1a-2ffa-42de-ada0-c146b99b8ded)

**Comment by mjs3350** [comment] 2023-05-26 21:43
I came here to mention that label tab makes contact with the base before the stacking lip when stacking bins.  Looks like this is the same issue.

**Comment by tache** [comment] 2023-07-11 15:48
Is this still an open issue? I see releases, but they do not mention this issue.

**Comment by Le0Michine** [comment] 2023-07-14 15:46
it is still open, I was gonna take another look, but have been busy lately so other things were prioritized

**Comment by Le0Michine** [comment] 2023-07-14 21:23
did a bit of experimentation and it seems like tab and compartment walls can be adjusted to be slightly lower, here is how it looks like with 0.25mm clearance

![Screenshot 2023-07-14 142103](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/2707008/9111f4e7-8040-4dec-a3a4-afa88383679f)
![Screenshot 2023-07-14 142006](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/2707008/3d8e9d22-3d20-4642-a7bb-1ced7cfa6ab0)
![Screenshot 2023-07-14 141937](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/2707008/ba2fb7fd-f123-4174-8272-ef416e4ced94)

**Comment by Le0Michine** [comment] 2023-07-14 22:53
pushed updated version, you can update and try it out, let me know if you still seeing the issue

**Comment by tache** [comment] 2023-07-15 00:54
Great! I will give it a spin when my long print finishes.

**Comment by tache** [comment] 2023-07-19 05:05
Hey this is much better, but a tiny bit off. I am thinking somewhere like 1 mm, but not more than 1.5mm

## Tested with two 2x3 bins, with a dividers as shown. 
![Bin-Stack - 1](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/594187/2cb3e638-5efb-4d0a-aabc-9b6d989c3ad9)

## 2x3 bin bottoms. 
![Bin-Stack - 4](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/594187/9f0c2871-e3b1-4b61-b053-bb69f5007b4b)

## This picture has the bin with the divider longways on the bottom. So the divider does not hit the bottom since it is in the middle cutout.
![Bin-Stack - 2](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/594187/aaac387e-292a-4ea6-93ca-b257922403e3)

## This picture has the bin with the divider shortways on the bottom. You can see that the bottom of the top sits on the divider  
![Bin-Stack - 3](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/594187/9b8be9d9-872e-4cc9-90be-a6825528918f)

**Comment by Le0Michine** [comment] 2023-07-19 06:15
Hmm, can you confirm if the bottom of those bins is flat? Not sure if just the corners curled up or the whole thing shrank.

Also, what layer height you used?

**Comment by tache** [comment] 2023-07-21 05:03
Yes they are flat. Here are the settings.

![Bin-Stack - 5](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/594187/b68bae00-b5ff-403d-8d5a-6a911b988912)

![settings](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/594187/e123332e-776e-412d-bf30-0dc6c5d4bf02)

**Comment by tache** [comment] 2023-07-21 05:11
I just noticed another artifact on the dividers. It bleeds through to the outside. Here are the two bins, one had a divider in the short side, then other in the long side. 

![Bin-Stack - 6](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/594187/dc3aed8f-cfbf-4007-b1a3-889b17d5f49c)

![Bin-Stack - 7](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/594187/4cc68237-4107-420c-8ce1-32dfbf510dc8)

**Comment by Le0Michine** [comment] 2023-07-22 19:29
The last one is likely related to your print settings. That also might be unavoidable for thinner walls.

**Comment by Le0Michine** [comment] 2023-07-22 19:31
here you can barely see it, even though layers quality is quite bad for this particular print

![IMG_3125](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/2707008/25e7d956-27d2-46e7-a909-416a1c68e654)

**Comment by Le0Michine** [comment] 2023-08-07 18:51
I'm gonna close this for now, feel free to reopen if the issue still persists

**Closed by Le0Michine** 2023-08-07 18:51 UTC
Labels: Printability issue
