### ISSUE TITLE
Faulty bins in latest Fusion 360

### ISSUE THREAD

**Issue by rj-040** [Le0Michine/FusionGridfinityGenerator#56] opened 2023-10-31 19:05 UTC
Looks like latest version of Fusion 360 somewhat breaks your super-nice plugin.
There is a part of the top-lip that doesn't get created.
https://imgur.com/a/0BROEDY

Also, when I try to make shelled bins with slightly thicker walls, I get an error message, and the bin isn't created. (haven't been able to copy it).
I change from 1.2 mm to 1.8 mm. This might not be due to the new version of Fusion, as I haven't tried this before.

The version of Fusion 360 I run is: 
Fusion 360 2.0.17710 arm64 [Native] 
Active Plan: Personal
macOS 14.1 (23B74) on Mac13,1

**Comment by pyrho** [comment] 2023-11-02 10:42
I'm also seeing this on the latest update 2.0.17710 (win), have not changed anything from my usual workflow so I suspect it's due to the update.

**Comment by split141** [comment] 2023-11-03 15:03
> I took a look at the code, when creating bins, in "sketch 6" (using the default input options) the rectangle is centered on the origin instead of having one of its points on the origin.
> 
> The following code fixes it for me (editing the python file in `C:/Users/xxxx/AppData/Roaming/Autodesk/ApplicationPlugins/GridfinityGenerator.bundle/Contents/GridfinityGenerator.py` (you can find the path in the "Scripts and Add-ins" menu in fusion):
> 
> ```diff
> diff --git a/lib/gridfinityUtils/binBodyLipGenerator.py b/lib/gridfinityUtils/binBodyLipGenerator.py
> index 14fa2ec..85f607d 100644
> --- a/lib/gridfinityUtils/binBodyLipGenerator.py
> +++ b/lib/gridfinityUtils/binBodyLipGenerator.py
> @@ -115,7 +115,7 @@ def createGridfinityBinBodyLip(
>      sketchUtils.createRectangle(
>          actualLipBodyWidth,
>          actualLipBodyLength,
> -        adsk.core.Point3D.create(-actualLipBodyWidth / 2, -actualLipBodyLength / 2, 0),
> +        adsk.core.Point3D.create(0, 0, 0),
>          topChamferSketch,
>      )
>      topChamferNegativeVolume = extrudeUtils.simpleDistanceExtrude(
> ```
> 
> I'm not 100% on what I'm doing here, this might break other things, hence I won't open a PR, this is simply a workaround for now.

Thank you for the fix, worked for me!

**Comment by rj-040** [comment] 2023-11-03 15:10
Great work, @pyrho 
@Le0Michine What are your thoughts? Could this fix be implemented in your code?

**Comment by Le0Michine** [comment] 2023-11-03 16:09
hi, thanks for reporting this, looking into this

**Comment by Le0Michine** [comment] 2023-11-03 16:32
pushed an update, works for me locally, would appreciate it if you could try it out in your environment to confirm if it's working.

The problem appears to be related to Fusion update as previously sketch origin would be in a different spot, applied suggested change with slight modification which would hopefully protect against future fusion updates

```
topChamferSketch.modelToSketchSpace(adsk.core.Point3D.create(0, 0, topChamferSketch.origin.z)),
```

**Comment by Le0Michine** [comment] 2023-11-03 16:33
I'll kick off update process in Autodesk app store later

**Comment by pyrho** [comment] 2023-11-03 16:38
> pushed an update, works for me locally, would appreciate it if you could try it out in your environment to confirm if it's working.
> 
> The problem appears to be related to Fusion update as previously sketch origin would be in a different spot, applied suggested change with slight modification which would hopefully protect against future fusion updates
> 
> ```
> topChamferSketch.modelToSketchSpace(adsk.core.Point3D.create(0, 0, topChamferSketch.origin.z)),
> ```

I can confirm the issue is fixed using your latest changes to `binBodyLipGenerator.py`.

Thank you @Le0Michine !

**Comment by Le0Michine** [comment] 2023-11-04 03:10
looked into shell bin issue, it seems shell feature isn't able to solve multi base bin for wall thickness larger than 1.6mm. Unfortunately there doesn't seem to be a simple way to solve it

**Comment by rj-040** [comment] 2023-11-04 08:16
> looked into shelled bin issue, it seems shell feature isn't able to solve multi base bin for wall thickness larger than 1.6mm, it works with 1x1 bin but not with anything else. Unfortunately there doesn't seem to be a simple way to solve it

Ok, thanks. No major problem. I'll try out 1.6mm instead of 1.8mm.

**Comment by Le0Michine** [comment] 2023-11-04 22:30
the change is added into new release https://github.com/Le0Michine/FusionGridfinityGenerator/releases/tag/v1.2.7.0, pending update of the app in the autodesk app store, will keep this open until update comes through to avoid potential duplicates

**Comment by rj-040** [comment] 2023-11-07 18:22
@Le0Michine how long does it typically take for new versions to appear on the Autodesk page?
Thought I'd wait until 1.2.7 appears there.

**Comment by Le0Michine** [comment] 2023-11-07 19:32
that's hard to tell. Each update goes through manual review there and can take anywhere from a few days to couple weeks, all I can say is that I initiated it and nobody reached out to me yet, I'll switch [1.2.7 to release here](https://github.com/Le0Michine/FusionGridfinityGenerator/releases) once update goes through in the store. I'll also post an update here when that happens

**Comment by Boomhowre** [comment] 2023-11-09 20:07
Love this plugin! For what it's worth, in addition to the top lip issue - I am no longer able to create magnet cutouts on bins at 6mm x 2mm (default size works fine, but I like to press fit them rather than glue)

**Comment by Boomhowre** [comment] 2023-11-09 20:13
Adding to my comment below - just realized if I choose hollow body it works fine. Dang Noob.

**Comment by IDKwatMdoin** [comment] 2023-11-17 04:35
Speaking of noob how do I use the update 1.2.7 from here (github)? 

I'm running:
Fusion 360 2.0.17721 x86_64
Active Plan: Personal
Windows 10 Pro 22H2

**Comment by Le0Michine** [comment] 2023-11-17 08:18
You can follow installation instruction here https://github.com/Le0Michine/FusionGridfinityGenerator#from-source-code

also the new version just got published in the app store, so you should be able to download update from there https://apps.autodesk.com/FUSION/en/Detail/Index?id=7197558650811789&appLang=en&os=Win64

**Comment by rj-040** [comment] 2023-11-17 08:54
I just "upgraded" (i.e. manually installed) 1.2.7 from the Autodesk App Store. It looks to work great.
Thank you for your work, @Le0Michine

**Comment by Le0Michine** [comment] 2023-11-17 19:51
fix is released, closing this

**Closed by Le0Michine** 2023-11-17 19:51 UTC
