### ISSUE TITLE
Bin wall thickness too thin above label tab

### ISSUE THREAD

**Issue by thedansu** [Le0Michine/FusionGridfinityGenerator#44] opened 2023-08-27 23:12 UTC
The wall thickness above the label tab is smaller than the specified amount, leading to an awkward overhang. I generated a bin with 1.2 mm wall thickness but above the label tab, the wall is only 0.5mm.

![Screenshot 2023-08-27 160848](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/53230783/e52c419f-b9a0-4566-aa3a-6cabdeabf820)

**Comment by thedansu** [comment] 2023-08-27 23:53
Looks like each of the inner cutout sketches are dimensioned with the correct wall thickness except for the final one, adding 0.7mm to the label tab side, resulting in too thin of a wall when extruded/cut.
![Screenshot 2023-08-27 165204](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/53230783/796ca92c-c73d-4244-9461-2a85e49bc060)

**Comment by Le0Michine** [comment] 2023-08-29 22:14
thanks for creating the issue, I was able to reproduce it, looks like it is caused by extra offset created by scoop

![image](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/2707008/99daa37b-6943-4878-9fe8-69c9852639c9)

**Comment by Le0Michine** [comment] 2023-09-18 15:26
fixed in v1.2.6.0

**Closed by Le0Michine** 2023-09-18 15:26 UTC
Labels: bug
