### ISSUE TITLE
"Compartment depth" setting does not work as expected?

### ISSUE THREAD

**Issue by lutorm** [Le0Michine/FusionGridfinityGenerator#93] opened 2024-03-20 15:31 UTC
Changing the "compartment depth" when configuring the bin compartments changes the height of the bottom of the compartment (by filling in the compartment) not the top. Maybe that's what was intended, but it seems pointless to just remove volume. I thought it could be used to change the height of the divider wall, which seems more useful to me. Having divider walls not extend fully up to through the bin makes it easier to get things out and often you don't need a full divider to avoid mixing things up.

I guess I can do what I want by manually extruding the divider walls down after the bin is generated, but it's a bit of a pain.

**Comment by Le0Michine** [comment] 2024-04-04 03:34
compartment depth was intended to allow various depth for individual compartments and is specified per compartment, currently there is no option for customisation wall height. Wall height is already mentioned in #92 so I'm going to close this issue

**Closed by Le0Michine** 2024-04-04 03:34 UTC
